Merge upstream changes since August 2020
Should fix nameserver issue.

nixos-infect: curl -L to follow 301 redirect (#55)

Improve providers fix dns (#58)

* remove digitalocean as default; fix digitalocean dns; update channels

fixes #53
fixes #49

* fix doNetConf check

random fixes (#63)

* use the nameservers

That variable was being set, but not used

* fix shellcheck issues

xzcat dep check

nameserver parsing fix

removing some cruft

rewrite loopback namservers to 8.8.8.8

Prefer to if to '&&' (#64)

doNetConf check always true

Co-authored-by: Eric Litak <elitak@gmail.com>

avoid using NIX_PATH in resulting hardware-configuration.nix (#65)

This makes the resulting hardware-configuration.nix usable from a system
that is a nix flake without having to replace that usage of NIX_PATH first.

diff --git a/holo-hydra-create b/holo-hydra-create
--- a/holo-hydra-create
+++ b/holo-hydra-create
@@ -16,7 +16,7 @@ makeConf() {
   done
   local network_import=""
 
-  [ "$PROVIDER" = "digitalocean" ] && network_import="./networking.nix # generated at runtime by nixos-infect"
+  [[ -n "$doNetConf" ]] && network_import="./networking.nix # generated at runtime by nixos-infect"
   cat > /etc/nixos/configuration.nix << EOF
 { ... }: {
   imports = [
@@ -36,20 +36,15 @@ makeConf() {
 EOF
   # If you rerun this later, be sure to prune the filesSystems attr
   cat > /etc/nixos/hardware-configuration.nix << EOF
-{ ... }:
+{ modulesPath, ... }:
 {
-  imports = [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix> ];
+  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
   boot.loader.grub.device = "$grubdev";
   fileSystems."/" = { device = "$rootfsdev"; fsType = "ext4"; };
 }
 EOF
 
-  if [ "$PROVIDER" = "digitalocean" ]
-  then
-    makeNetworkingConf
-  else
-    true
-  fi
+  [[ -n "$doNetConf" ]] && makeNetworkingConf || true
 }
 
 makeNetworkingConf() {
@@ -82,8 +77,12 @@ EOF
     extraRules1=""
   fi
 
-  nameservers=($(grep ^nameserver /etc/resolv.conf | cut -f2 -d' '))
-  if [ "$eth0_name" = eth* ]; then
+  readarray nameservers < <(grep ^nameserver /etc/resolv.conf | sed -r \
+    -e 's/^nameserver[[:space:]]+([0-9.a-fA-F:]+).*/"\1"/' \
+    -e 's/127[0-9.]+/8.8.8.8/' \
+    -e 's/::1/8.8.8.8/' )
+
+  if [[ "$eth0_name" = eth* ]]; then
     predictable_inames="usePredictableInterfaceNames = lib.mkForce false;"
   else
     predictable_inames="usePredictableInterfaceNames = lib.mkForce true;"
@@ -93,9 +92,7 @@ EOF
   # This file was populated at runtime with the networking
   # details gathered from the active system.
   networking = {
-    nameservers = [$(for a in "${nameservers[@]}"; do echo -n "
-      \"$a\""; done)
-    ];
+    nameservers = [ ${nameservers[@]} ];
     defaultGateway = "${gateway}";
     defaultGateway6 = "${gateway6}";
     dhcpcd.enable = false;
@@ -120,19 +117,6 @@ EOF
   '';
 }
 EOF
-  #! /usr/bin/env bash
-  # NB put your semi-sensitive (not posted to github) configuration in a separate
-  # file and include it via this customConfig() function. e.g.:
-  #  customConfig() {
-  #    cat > /etc/nixos/custom.nix << EOF
-  #    { config, lib, pkgs, ... }: {
-  #    }
-  #    EOF
-  #  }
-  #
-  # then you can add the files in configuration.nix's imports above and run something like:
-  #   cat customConfig nixos-infect | root@targethost bash
-  if [[ "$(type -t customConfig)" == "function" ]]; then customConfig; fi
 }
 
 makeSwap() {
@@ -145,8 +129,8 @@ makeSwap() {
 }
 
 removeSwap() {
-    swapoff -a
-    rm -vf /tmp/nixos-infect.*.swp
+  swapoff -a
+  rm -vf /tmp/nixos-infect.*.swp
 }
 
 prepareEnv() {
@@ -206,6 +190,9 @@ checkEnv() {
   which bzcat || (which yum && yum install -y bzip2) \
               || (which apt-get && apt-get update && apt-get install -y bzip2) \
               || true
+  which xzcat || (which yum && yum install -y xz-utils) \
+              || (which apt-get && apt-get update && apt-get install -y xz-utils) \
+              || true
   which curl  || fakeCurlUsingWget \
               || (which apt-get && apt-get update && apt-get install -y curl) \
               || true
@@ -214,6 +201,7 @@ checkEnv() {
 
   req curl || req wget || { echo "ERROR: Missing both curl and wget"; return 1; }
   req bzcat            || { echo "ERROR: Missing bzcat";              return 1; }
+  req xzcat            || { echo "ERROR: Missing xzcat";              return 1; }
   req groupadd         || { echo "ERROR: Missing groupadd";           return 1; }
   req useradd          || { echo "ERROR: Missing useradd";            return 1; }
   req ip               || { echo "ERROR: Missing ip";                 return 1; }
@@ -225,7 +213,9 @@ infect() {
   # Add nix build users
   # FIXME run only if necessary, rather than defaulting true
   groupadd nixbld -g 30000 || true
-  for i in {1..10}; do useradd -c "Nix build user $i" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" nixbld$i || true; done
+  for i in {1..10}; do
+    useradd -c "Nix build user $i" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" "nixbld$i" || true
+  done
   # TODO use addgroup and adduser as fallbacks
   #addgroup nixbld -g 30000 || true
   #for i in {1..10}; do adduser -DH -G nixbld nixbld$i || true; done
@@ -268,6 +258,7 @@ infect() {
 
 [[ -z "$PROVIDER" ]]    && PROVIDER="digitalocean"
 [[ -z "$NIX_CHANNEL" ]] && NIX_CHANNEL="nixos-19.09"
+[ "$PROVIDER" = "digitalocean" ] && doNetConf=y # digitalocean requires detailed network config to be generated
 
 prepareEnv
 makeSwap # smallest (512MB) droplet needs extra memory!
